version: '3.8'
services:
  postgres-primary:
    image: postgres:15-alpine
    container_name: pg_primary
    environment:
      - POSTGRES_DB=chat_primary
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_primary_data:/var/lib/postgresql/data
    command: >
      postgres -c wal_level=logical
               -c max_wal_senders=10
               -c max_replication_slots=10

  postgres-replica:
    build:
      context: .  # path to project folder
      dockerfile: Dockerfile.replica
    container_name: pg_replica
    depends_on:
      - postgres-primary
    environment:
      - POSTGRES_DB=chat_replica
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - pg_replica_data:/var/lib/postgresql/data

volumes:
  pg_primary_data:
  pg_replica_data: